### ISSUE TITLE
Fix Navigation

### ISSUE THREAD

**Issue by pegasus-lynx** [COPS-IITBHU/cops-website#20]
On decreasing the width of the window, the navigation bar shifts to another line. It is expected that the navigation menu stays on the same line. 
Refer to the image below.
![cops-navigation](https://user-images.githubusercontent.com/39705934/60028315-c71b8b80-96bc-11e9-81e6-f075d9f6ee3b.png)

**Comment by arron-tij** [comment]
Changed the position of the header to make the nav bar responsive.

**Comment by arv-77** [comment]
I have made the navigation bar responsive.

**Comment by arv-77** [comment]
Kindly confirm if there is any error in my PR

**Comment by shivanshs9** [comment]
Fixed.
