### ISSUE TITLE
COPS Logo in homepage

### ISSUE THREAD

**Issue by pegasus-lynx** [COPS-IITBHU/cops-website#22]
COPS logo is missing on the website. 
Add it in the header.

**Comment by arv-77** [comment]
I want to attempt to solve this issue.

**Comment by manvendra09** [comment]
i am interested to work on this issue ....i want to know your thoughts about logo...

**Comment by arv-77** [comment]
The logo has to be added next to the cops block, right?

**Comment by pegasus-lynx** [comment]
> The logo has to be added next to the cops block, right?

Sorry, but the issue is being assigned to the other guy. But keep the spirit high and keep contributing.

**Comment by pegasus-lynx** [comment]
> i am interested to work on this issue ....i want to know your thoughts about logo...

The logo has to be in the center of the header. Not in the navigation bar. Navigation bar should not be messed with. 


![cop-logo](https://user-images.githubusercontent.com/39705934/62389024-606f7480-b57c-11e9-9a11-778f7de2a35c.png)

This logo is to be used in the header.

Basically, you have to use *Agency FB* font for creating the logo.
And, do keep in mind that while you are using text to create the logo try to keep the ratio of font siize appropriate for all screen sizes.

**Comment by manvendra09** [comment]
<link href="http://allfont.net/allfont.css?fonts=agency-fb" rel="stylesheet" type="text/css" />
    <style>
      body {
        font-family: 'Agency FB', arial;
        font-size: 48px;
        text-shadow: 4px 4px 4px #aaa;
      }
    </style>

i used the above url for the logo but its not working

**Comment by manvendra09** [comment]
<link href="http://allfont.net/allfont.css?fonts=agency-fb" rel="stylesheet" type="text/css" />
    <style>
      body {
        font-family: 'Agency FB', arial;
        font-size: 48px;
        text-shadow: 4px 4px 4px #aaa;
      }
    </style>


i used the above url for logo but its not working......

**Comment by manvendra09** [comment]
mixed content detected what should i do??

**Comment by pegasus-lynx** [comment]
> mixed content detected what should I do??

That is not an issue. But the problem with the PR is that we asked you to use the Agency FB font to write the logo int the header section. But instead, you used the above image directly.  
And by the header, we meant the section gray section just below the navbar.

**Comment by manvendra09** [comment]
i haven't use the image ..i made a css file for the logo ...in static folder..

**Comment by manvendra09** [comment]
i will add it in the header

**Comment by subodhk01** [comment]
https://github.com/COPS-IITBHU/cops-website/pull/67

**Comment by shivanshs9** [comment]
Merged.
