### ISSUE TITLE
Projects section unresponsive

### ISSUE THREAD

**Issue by pegasus-lynx** [COPS-IITBHU/cops-website#23]
The project section on the home page is unresponsive. 
On decreasing the width of the window, the projects section appears as seen in the picture. Refer to the image below.

![projects](https://user-images.githubusercontent.com/39705934/60028776-92f49a80-96bd-11e9-8cdf-82db3f3e9c94.png)

**Comment by krashish8** [comment]
Created a PR to make the Project Section responsive.

**Comment by Eerie16** [comment]
Merged.
