### ISSUE TITLE
POTW unresponsive

### ISSUE THREAD

**Issue by pegasus-lynx** [COPS-IITBHU/cops-website#25]
On smaller screens, the contents of the POTW page clutter. Refer to the image below.
![potw](https://user-images.githubusercontent.com/39705934/60029381-ace2ad00-96be-11e9-9188-7d5e3666adfc.png)

Make changes in the style of the page for smaller screens.

**Comment by arv-77** [comment]
I have tried to make the POTW page responsive by pushing the problem and editorial button below the problem title when the width of the page is not sufficient to display the content correctly.

**Comment by pegasus-lynx** [comment]
> I have tried to make the POTW page responsive by pushing the problem and editorial button below the problem title when the width of the page is not sufficient to display the content correctly.

@arvindmuralie77 Thanks for your contribution. But from the next time before making a PR/ working on an issue, please leave a comment in the issue so that the maintainers can know and discuss the issue further.

And make a PR, so that we can review your work. :+1:

**Comment by shivanshs9** [comment]
Fixed.
