### ISSUE TITLE
Blog page unresponsive

### ISSUE THREAD

**Issue by pegasus-lynx** [COPS-IITBHU/cops-website#26]
This page has few issues with smaller screens. 
For smaller screens 
- The camera icon appears on the next line. It is expected to stay on the same line.
- The whole content is indented towards the right.

Refer to the images below.
![blog_and_search](https://user-images.githubusercontent.com/39705934/60029667-35f9e400-96bf-11e9-8aef-8a00141a1577.png)

![blog-sm](https://user-images.githubusercontent.com/39705934/60029876-9557f400-96bf-11e9-8d38-3d4b169270e2.png)

**Comment by krashish8** [comment]
I've tried to fix this issue.

**Comment by krashish8** [comment]
Created a PR to fix this issue.

**Comment by shivanshs9** [comment]
Merged! :confetti_ball:
