### ISSUE TITLE
Search icon

### ISSUE THREAD

**Issue by pegasus-lynx** [COPS-IITBHU/cops-website#27]
Search icon on the blog page needs to be modified. 
It should be more like a floating action button fixed at the bottom of the page. 
( similar to the social icons on the homepage )

**Comment by arron-tij** [comment]
I am currently working on this issue and would likely be submitting a fix by today.

**Comment by arron-tij** [comment]
I think the latest PR ought to be a satisfactory fix.

**Comment by shivanshs9** [comment]
Fixed!
