### ISSUE TITLE
CSOC Leaderboard

### ISSUE THREAD

**Issue by pegasus-lynx** [COPS-IITBHU/cops-website#28]
CSOC Leaderboard section needs to be added in the CSOC page.
The structure of the leaderboard should be similar to that of the POTW page - 

- should have three dropdown lists (one for each ML, Dev, CP )
- each list should display a table listing the name, institute, and points of the participants.

**Comment by arron-tij** [comment]
I want to work on this issue and have a query that I need to just create a accordion type framework like the POTW section right? And the data would be fed by you by creating files according to the names I use in framework?

**Comment by arron-tij** [comment]
I have made a demo fix for this issue. Please review the PR so that I can make a new and final PR.

**Comment by shivanshs9** [comment]
Stale.
