### ISSUE TITLE
Collapsible Timeline

### ISSUE THREAD

**Issue by Eerie16** [COPS-IITBHU/cops-website#47]
The timeline in its present state occupies a lot of vertical space which is bad design for navigation.
It should display a preset amount( say x) of entries by default and have a button to expand the list.

**Comment by subodhk01** [comment]
https://github.com/COPS-IITBHU/cops-website/pull/68

**Comment by subodhk01** [comment]
https://github.com/COPS-IITBHU/cops-website/pull/70
