### ISSUE TITLE
Alignment Issue in CSOC Page

### ISSUE THREAD

**Issue by Eerie16** [COPS-IITBHU/cops-website#51]
The entire CSOC page has content shifted to the right hand side. Note that the issue is only in the desktop site.
![csoc_issue](https://user-images.githubusercontent.com/33527566/62709709-8761f680-ba13-11e9-9fc5-da7d93c68370.png)

**Comment by krashish8** [comment]
@Eerie16 I think PR https://github.com/COPS-IITBHU/cops-website/pull/42 resolves this issue, but it was closed.

Please check it or should I make another PR?

**Comment by Eerie16** [comment]
For some reason, the issue is only limited to certain devices.
Anyways, I've reopened the PR, so we're good to go :+1:
