### ISSUE TITLE
Navbar menu not visible with COPS logo

### ISSUE THREAD

**Issue by subodhk01** [COPS-IITBHU/cops-website#72]
<img width="1680" alt="Screenshot 2020-02-05 at 15 45 49" src="https://user-images.githubusercontent.com/19875783/73870518-3cb22180-4872-11ea-9427-2d0e03456ba2.png">
The dropdown menu and COPS logo are getting intermixed. The dropdown menu should have a background so that its contents doesn't get mixed with the COPS logo.

**Comment by shivanshs9** [comment]
I guess we could have a black background for dropdown nav.

**Comment by king-11** [comment]
I want to work on this issue @shivanshs9

**Comment by shivanshs9** [comment]
@king-11 you still working on it?

**Comment by king-11** [comment]
@shivanshs9 I am not able to work out the issue properly so i have stopped working on it. Sorry for delay caused.

**Comment by AnonySharma** [comment]
I want to work on this issue @shivanshs9.

**Comment by shivanshs9** [comment]
Closed by #89
