### ISSUE TITLE
Arrow direction is wrong when the POTW page loads

### ISSUE THREAD

**Issue by subodhk01** [COPS-IITBHU/cops-website#73]
<img width="1183" alt="Screenshot 2020-02-06 at 00 09 29" src="https://user-images.githubusercontent.com/19875783/73872319-7df80080-4875-11ea-8319-79ebff1c9ac0.png">
When the POTW page ( <a href="https://copsiitbhu.co.in/resources/potw/">POTW</a> ) loads, the direction of all the arrows is opposite. After clicking any one of them the directions get right.

**Comment by AnonySharma** [comment]
Resolved now!

**Comment by AnonySharma** [comment]
I'm resolving this issue.

**Comment by shivanshs9** [comment]
Closed via 3c8b1bb24d75f690abe15bd6e421419044138f0a
