### ISSUE TITLE
Hover effect not working properly in navbar

### ISSUE THREAD

**Issue by ghost** [COPS-IITBHU/cops-website#85]
When the cursor hovers the navbar text with a drop-down, it highlights but to restore it is required to click outside. It works fine with text having no drop-down.

![web_issue](https://user-images.githubusercontent.com/57213538/76340074-fcd2d400-6320-11ea-9e47-05c7e205da5f.gif)

**Comment by shivanshs9** [comment]
Great catch! Can you please give it a try to solve it?
