### ISSUE TITLE
Spacing in COPS logo disturbed

### ISSUE THREAD

**Issue by subodhk01** [COPS-IITBHU/cops-website#86]
After the new cdn for Agency FB font was used, spacing between the letters of the COPS logo is disturbed
<img width="538" alt="Screenshot 2020-03-11 at 16 09 18" src="https://user-images.githubusercontent.com/19875783/76408317-c6de3000-63b2-11ea-95e4-15a216bf4d62.png">

**Comment by subodhk01** [comment]
#87

**Comment by shivanshs9** [comment]
Fixed by #87
