### ISSUE TITLE
contents of navbar for resources,CSOC and DEVEXTRAVAGANZA are coming shifted to left

### ISSUE THREAD

**Issue by SATAKSHI08** [COPS-IITBHU/cops-website#90]

**Comment by shivanshs9** [comment]
Can you describe the issue in more details? It'll be great if you could provide screenshot and expected look.

**Comment by SATAKSHI08** [comment]
I mean like drop down for CSOC is coming below RESOURCES and for RESOURCES it is coming below BLOG,it should be like just below as it is coming in case of DEV EXTRAVAGANZA.

**Comment by SATAKSHI08** [comment]
![image](https://user-images.githubusercontent.com/56965113/76855363-fe4b5180-6876-11ea-82ed-755a0d9c71fe.png)
![image](https://user-images.githubusercontent.com/56965113/76855391-0c996d80-6877-11ea-85fe-1d9af694fb7c.png)
